# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "boxen/ubuntu-24.04"
  config.vm.box_check_update = false
  
  # define k3s nodes
  (1..3).each do |number|
    name = "k#{number}build"

    config.vm.define name do |node|
      node.vm.network 'public_network', ip: "192.168.6.12#{number}", netmask: "21",  bridge: "enp6s0"
      # https://developer.hashicorp.com/vagrant/docs/networking/public_network#disable-auto-configuration
      node.vm.network 'forwarded_port', id: 'ssh', host: "812#{number}", guest: "22"
      node.vm.hostname = name
    end
  end

  config.vm.provider 'virtualbox' do |vb|
    # nest inside loops above for targeting specific nodes
    vb.memory = '8192'
    vb.cpus = 4
  end

  # install fish for my provisioning script, and other initial config AND THEN REBOOT
  config.vm.provision 'shell', name: 'early', reboot: true, inline:<<EOF

# disable ipv6 (for my demo network)
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"/' /etc/default/grub
sudo update-grub

# expand LV/FS to include what's already available in the PV/VG (but not allocated initially)
sudo lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv
sudo resize2fs /dev/ubuntu-vg/ubuntu-lv

sudo apt update
sudo apt install -y fish
# bug in OOB kernel 6.8.0-57-generic, so upgrade it:
sudo apt install --yes linux-generic-hwe-24.04

EOF

  config.vm.provision 'shell', path: "../mac/bootstrap/dotfiles.fish", privileged: false
end

